[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python3.11 -m venv /opt/venv",
  "/opt/venv/bin/pip install --prefer-binary --no-cache-dir -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python -u main.py"
